import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header"; // Adjust the import path as necessary
import Home from "@/components/Home/Home";
import { SearchProvider } from "@/contexts/SearchContext";
import Footer from "@/components/Footer/Footer";
import NewsletterSignup from "@/components/NewsletterSignup/NewsletterSignup";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const handleSearch = (query) => {
    // Handle search functionality
    console.log("Search query:", query);
  };
  return (
    <SearchProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <Header />
          {children}
          <NewsletterSignup />
          <Footer />
        </body>
      </html>
    </SearchProvider>
  );
}
