/**
 * Custom card-level excerpts for journal articles.
 * These are shorter, punchier summaries optimized for card display,
 * distinct from the article's `lead` field.
 */
export const CARD_EXCERPTS = {
  "water-as-teacher": "Water does not force its way. It finds it. On the oldest teacher and what it knows about patience, persistence, and letting go.",
  "learning-to-be-a-beginner": "Somewhere between childhood and now, we lost the willingness to be bad at things. Reclaiming it might be the most freeing thing you ever do.",
  "the-freedom-of-small-spaces": "We chase expansiveness, but some of the deepest peace lives in the smallest moments and the tightest corners.",
  "hunger-beyond-food": "Sometimes the thing you are reaching for in the kitchen is not in the kitchen at all. On recognizing what you truly need.",
  "the-ritual-of-repair": "We discard what is broken. But some things were meant to be mended, and the mending is where the beauty lives.",
  "on-grief-without-a-name": "Not all grief comes with a funeral. Some losses are so quiet that you do not realize you are mourning until the ache has already settled in.",
  "what-the-garden-teaches": "A garden does not care about your timeline. It grows at its own pace, and it will teach you to do the same.",
  "the-practice-of-receiving": "We practice giving so often that we forget: receiving is a skill too, and most of us are out of practice.",
  "silence-as-a-language": "We fill silence because we are afraid of what it might say. But silence is not empty. It is full of answers.",
  "the-kindness-of-routine": "Routine is not the enemy of freedom. It is the quiet structure that makes freedom possible.",
  "sleep-as-surrender": "What if sleep is the one thing that cannot be optimized, only invited? On letting go of the performance of rest.",
  "tending-the-inner-weather": "Emotions are not problems to solve. They are weather to notice, name, and let pass.",
  "the-long-exhale": "The science and ritual behind a longer breath out, and why your nervous system has been waiting for it.",
  "on-walking-without-a-destination": "What happens when you walk with no route, no earbuds, and no purpose other than presence.",
  "the-body-keeps-a-quiet-score": "Your body has been keeping notes long before your mind started paying attention. On learning to listen.",
  "the-art-of-gentle-transitions": "How learning to pause between tasks can protect your energy and bring ease to your day.",
  "digital-minimalism-in-a-loud-world": "Practical ways to clear the digital noise and reclaim your attention for the things that matter.",
  "finding-ritual-in-the-kitchen": "How turning cooking into a sensory practice can ground you in the present moment.",
  "the-gentle-discipline-of-saying-no": "Saying no is not selfish. It is the boundary that allows your yes to have true meaning.",
  "cultivating-a-mindful-workspace": "Simple adjustments to your physical and mental environment to bring more peace to your work hours.",
  "the-art-of-doing-nothing": "Why rest is not laziness, and how learning to be still changed the way I move through my days.",
  "morning-rituals-that-anchor-me": "A simple sequence of small acts that turns the first hour of the day into something sacred.",
  "letting-go-of-perfect": "Perfectionism kept me busy but never at peace. Here is what happened when I stopped chasing it.",
  "the-quiet-power-of-a-slow-morning": "What happens when you stop rushing through the first hours of your day and let them unfold at their own pace.",
  "breathing-through-the-overwhelm": "When everything feels like too much, three breaths can change the entire shape of the moment.",
  "seasonal-living-as-practice": "Aligning your rhythms with the natural world is one of the gentlest forms of self-care I know.",
  "the-weight-of-being-available": "On the quiet exhaustion of a life with no boundaries between reachable and resting.",
  "what-i-mean-when-i-say-gentle": "Gentleness is not weakness. It is the strongest way I know to move through a hard world.",
  "learning-to-sit-with-discomfort": "The urge to fix, flee, or distract is strong. But some feelings just need a witness.",
  "the-myth-of-balance": "What if balance is not a state to achieve but a conversation to keep having with yourself?",
};
