/**
 * Custom card-level excerpts for journal articles.
 * These are shorter, punchier summaries optimized for card display,
 * distinct from the article's `lead` field.
 */
export const CARD_EXCERPTS = {
  "the-practice-of-apologizing": "A genuine apology is not a performance. It is the willingness to name what you did and stand in the silence that follows.",
  "money-scarcity-and-enough": "We practice mindfulness with our breath and our food, but rarely with money. Financial awareness is the last honest frontier.",
  "living-alongside-pain": "Living with chronic pain is an invisible negotiation. On the quiet strength of adapting to a body that does not always cooperate.",
  "anger-as-information": "We suppress anger because we were taught it is dangerous. But anger is a signal, and silencing it means missing what it has to say.",
  "the-sound-of-your-own-voice": "The voice you know best is the one no one else has ever heard. On finding the real one underneath all the performing.",
  "the-body-you-are-in": "We learned to look at our bodies before we learned to live in them. Shifting from observer to inhabitant changes everything.",
  "rest-is-not-recovery": "You can rest without recovering. Understanding the difference is why your weekends still leave you exhausted.",
  "on-friendships-that-change-shape": "Not all friendships end with a fight. Some end with silence, and the grief of that quiet loss is one of the loneliest we carry.",
  "the-permission-to-weep": "We apologize for tears as if they were a failure. But crying is a release your body was designed to need.",
  "the-page-that-listens": "A journal does not solve anything. It listens. And sometimes, being heard by your own handwriting is enough.",
  "water-as-teacher": "Water does not force its way. It finds it. On the oldest teacher and what it knows about patience, persistence, and letting go.",
  "learning-to-be-a-beginner": "Somewhere between childhood and now, we lost the willingness to be bad at things. Reclaiming it might be the most freeing thing you ever do.",
  "the-freedom-of-small-spaces": "We chase expansiveness, but some of the deepest peace lives in the smallest moments and the tightest corners.",
  "hunger-beyond-food": "Sometimes the thing you are reaching for in the kitchen is not in the kitchen at all. On recognizing what you truly need.",
  "the-ritual-of-repair": "We discard what is broken. But some things were meant to be mended, and the mending is where the beauty lives.",
  "on-grief-without-a-name": "Not all grief comes with a funeral. Some losses are so quiet that you do not realize you are mourning until the ache has already settled in.",
  "what-the-garden-teaches": "A garden does not care about your timeline. It grows at its own pace, and it will teach you to do the same.",
  "the-practice-of-receiving": "We practice giving so often that we forget: receiving is a skill too, and most of us are out of practice.",
  "silence-as-a-language": "We fill silence because we are afraid of what it might say. But silence is not empty. It is full of answers.",
  "the-kindness-of-routine": "Routine is not the enemy of freedom. It is the quiet structure that makes freedom possible.",
  "sleep-as-surrender": "What if sleep is the one thing that cannot be optimized, only invited? On letting go of the performance of rest.",
  "tending-the-inner-weather": "Emotions are not problems to solve. They are weather to notice, name, and let pass.",
  "the-long-exhale": "The science and ritual behind a longer breath out, and why your nervous system has been waiting for it.",
  "on-walking-without-a-destination": "What happens when you walk with no route, no earbuds, and no purpose other than presence.",
  "the-body-keeps-a-quiet-score": "Your body has been keeping notes long before your mind started paying attention. On learning to listen.",
  "the-art-of-gentle-transitions": "The spaces between tasks are not dead time. They are where your nervous system catches up, and honoring them changes everything.",
  "digital-minimalism-in-a-loud-world": "Your attention is the most finite resource you own. Reclaiming it from constant notifications requires design, not just willpower.",
  "finding-ritual-in-the-kitchen": "How turning cooking into a sensory practice can ground you in the present moment and feed more than the body.",
  "the-gentle-discipline-of-saying-no": "Every yes carries a hidden no. Learning to decline with clarity and kindness is the boundary that lets your yes mean something.",
  "cultivating-a-mindful-workspace": "Your workspace shapes your attention. A few intentional changes to what you see and touch can shift the texture of an entire day.",
  "the-art-of-doing-nothing": "Why rest is not laziness, and how learning to be still changed the way I move through my days.",
  "morning-rituals-that-anchor-me": "A simple sequence of small acts that turns the first hour of the day into something sacred.",
  "letting-go-of-perfect": "Perfectionism kept me busy but never at peace. Here is what happened when I stopped chasing it.",
  "the-quiet-power-of-a-slow-morning": "What happens when you stop rushing through the first hours of your day and let them unfold at their own pace.",
  "breathing-through-the-overwhelm": "When everything feels like too much, three breaths can change the entire shape of the moment.",
  "seasonal-living-as-practice": "Aligning your rhythms with the natural world is one of the gentlest forms of self-care I know.",
  "the-weight-of-being-available": "On the quiet exhaustion of a life with no boundaries between reachable and resting.",
  "what-i-mean-when-i-say-gentle": "Gentleness is not weakness. It is the strongest way I know to move through a hard world.",
  "learning-to-sit-with-discomfort": "The urge to fix, flee, or distract is strong. But some feelings just need a witness.",
  "the-myth-of-balance": "Balance is not a destination. It is a shifting conversation about what needs your attention right now.",
};
