/**
 * Custom card-level excerpts for journal articles.
 * These are shorter, punchier summaries optimized for card display,
 * distinct from the article's `lead` field.
 */
export const CARD_EXCERPTS = {
  "the-silence-after-you-say-the-true-thing": "There is a silence that only comes after honesty. In the two seconds before the other person responds, the hands grip, the stomach drops, the lungs stop. Your body prepares for every possible future simultaneously. This is not courage; it is the price the nervous system pays for honest conversation.",
  "the-warmth-that-stays": "She left the room three minutes ago, and the cushion where she sat is warm. I put my hand on it, and something in my chest responds before my mind does. The hand reaches for every warm spot: the couch, the car seat, the pillow. Body awareness is how we read connection without words.",
  "the-age-you-started-believing-you-were-too-late": "A friend mentioned she was learning Italian, and my first response was a contraction in my chest: a flinch that meant you should have done that years ago. I was thirty-four. Some part of me had already decided that starting over was no longer possible.",
  "the-cup-you-still-make-for-two": "I make two cups of tea every morning, though I have lived alone for fourteen months. The hands do not decide. They reach for both mugs, fill the kettle to the same line, and by the time the mind catches up, one cup is for no one. Grief lives in the architecture of a shared morning.",
  "the-honest-shock-of-cold-water": "The water hit my shoulders and I made a sound I did not recognize. Four seconds of no thoughts. I had been meditating for two years and had never once achieved four seconds of no thoughts. Cold water does not wait for the mind to cooperate.",
  "the-argument-your-body-is-having-without-you": "The clenched jaw during the meeting you said you were fine with. The stomach that tightens before you say yes. The Sunday headache that arrives on schedule. Your body is not malfunctioning. It is disagreeing, and you have spent years treating its body signals as noise.",
  "the-wisdom-of-restless-hands": "We treat fidgeting as a failure of focus. But your restless hands are not interrupting your concentration. They are sponsoring it, doing the nervous system's work with whatever pen cap is within reach.",
  "the-hours-that-belong-to-someone-else": "No one marks the moment you become a caregiver. You simply begin doing more, and the more becomes the norm, and the norm becomes the shape of your entire week without anyone naming what has happened.",
  "the-arithmetic-of-worry": "There is a particular kind of arithmetic that happens at two in the morning. It does not use a calculator. It uses the ceiling. The numbers never add up, because fear is doing the counting.",
  "what-the-illness-left-behind": "The doctors signed you off. The blood work is normal. But the body has not forgotten. Recovery takes longer than medicine measures, because the body measures something else entirely.",
  "the-thing-you-make-badly": "A child paints without asking whether the painting is good. An adult cannot pick up a brush without the question arriving before the paint does. On reclaiming the right to create without purpose.",
  "the-door-you-close-quietly": "The almost was exhausting in a way that outright unhappiness would not have been, because unhappiness gives you permission to leave. The almost does not. The almost says: this could still work.",
  "what-the-empty-shelf-knows": "Objects hold more than space. They hold identity: the running shoes from when you ran, the sewing machine from when you were going to learn. Letting go means admitting something.",
  "the-city-that-does-not-know-you-yet": "The barista does not know your order. The neighbor does not nod. The streets hold none of your history. Moving is grief, even when you chose it, even when the new city is better by every measure.",
  "when-the-body-slows": "The shoulder protests a movement it used to make without comment. The ankle stiffens overnight. These are not failures. They are dispatches from a body becoming something new.",
  "the-small-hand-that-pulls-you-back": "No one tells you that the hardest part of parenting is not the sleeplessness. It is being needed in the present tense, over and over, by someone who will not let you be anywhere else.",
  "the-weather-inside-a-decision": "Before a decision becomes words, it is weather: nausea, sleeplessness, a clarity that arrives at two in the morning. Your body is not confused. It is processing.",
  "the-hours-no-one-sees": "Before the house wakes and after it sleeps, there is a version of you with no audience. She is not the lesser version. She is the one who holds everything else together.",
  "what-the-mirror-does-not-show": "The mirror shows what you look like. Your body knows what you feel like. Somewhere between those two, most of us lost track of which one to trust.",
  "the-courage-of-staying-still": "We celebrate the ones who leave. But sometimes the braver thing is staying exactly where you are and letting the difficulty finish what it came to do.",
  "the-taste-of-enough": "The body knows when it has had enough. It sends the signal quietly, and most of us have spent a lifetime learning to override it.",
  "what-the-body-holds-after": "The difficult thing ended, but the body kept holding on. On the quiet, ordinary work of letting the nervous system know that the danger has passed.",
  "the-edges-of-attention": "We sharpen our focus and lose the rest. But the periphery of attention is where the richest details of your day have been waiting, unnoticed.",
  "hands-that-remember": "Your hands carry a record of everything they have ever learned. Kneading, braiding, holding, mending: the body remembers what the mind lets go.",
  "the-conversation-you-are-not-having": "The things we do not say do not disappear. They settle between people, taking up the space where honesty used to live.",
  "the-intelligence-of-exhaustion": "We treat exhaustion as a scheduling problem. But the body is not asking for a better calendar. It is asking for a different structure entirely.",
  "the-practice-of-apologizing": "A genuine apology is not a performance. It is the willingness to name what you did and stand in the silence that follows.",
  "money-scarcity-and-enough": "We practice mindfulness with our breath and our food, but rarely with money. Financial awareness is the last honest frontier.",
  "living-alongside-pain": "Living with chronic pain is an invisible negotiation. On the quiet strength of adapting to a body that does not always cooperate.",
  "anger-as-information": "We suppress anger because we were taught it is dangerous. But anger is a signal, and silencing it means missing what it has to say.",
  "the-sound-of-your-own-voice": "The voice you know best is the one no one else has ever heard. On finding the real one underneath all the performing.",
  "the-body-you-are-in": "We learned to look at our bodies before we learned to live in them. Shifting from observer to inhabitant changes everything.",
  "rest-is-not-recovery": "You can rest without recovering. Understanding the difference is why your weekends still leave you exhausted.",
  "on-friendships-that-change-shape": "Not all friendships end with a fight. Some end with silence, and the grief of that quiet loss is one of the loneliest we carry.",
  "the-permission-to-weep": "We apologize for tears as if they were a failure. But crying is a release your body was designed to need.",
  "the-page-that-listens": "A journal does not solve anything. It listens. And sometimes, being heard by your own handwriting is enough.",
  "water-as-teacher": "Water does not force its way. It finds it. On the oldest teacher and what it knows about patience, persistence, and letting go.",
  "learning-to-be-a-beginner": "Somewhere between childhood and now, we lost the willingness to be bad at things. Reclaiming it might be the most freeing thing you ever do.",
  "the-freedom-of-small-spaces": "We chase expansiveness, but some of the deepest peace lives in the smallest moments and the tightest corners.",
  "hunger-beyond-food": "Sometimes the thing you are reaching for in the kitchen is not in the kitchen at all. On recognizing what you truly need.",
  "the-ritual-of-repair": "We discard what is broken. But some things were meant to be mended, and the mending is where the beauty lives.",
  "on-grief-without-a-name": "Not all grief comes with a funeral. Some losses are so quiet that you do not realize you are mourning until the ache has already settled in.",
  "what-the-garden-teaches": "A garden does not care about your timeline. It grows at its own pace, and it will teach you to do the same.",
  "the-practice-of-receiving": "We practice giving so often that we forget: receiving is a skill too, and most of us are out of practice.",
  "silence-as-a-language": "We fill silence because we are afraid of what it might say. But silence is not empty. It is full of answers.",
  "the-kindness-of-routine": "Routine is not the enemy of freedom. It is the quiet structure that makes freedom possible.",
  "sleep-as-surrender": "What if sleep is the one thing that cannot be optimized, only invited? On letting go of the performance of rest.",
  "tending-the-inner-weather": "Emotions are not problems to solve. They are weather to notice, name, and let pass.",
  "the-long-exhale": "The science and ritual behind a longer breath out, and why your nervous system has been waiting for it.",
  "on-walking-without-a-destination": "What happens when you walk with no route, no earbuds, and no purpose other than presence.",
  "the-body-keeps-a-quiet-score": "Your body has been keeping notes long before your mind started paying attention. On learning to listen.",
  "the-art-of-gentle-transitions": "The spaces between tasks are not dead time. They are where your nervous system catches up, and honoring them changes everything.",
  "digital-minimalism-in-a-loud-world": "Your attention is the most finite resource you own. Reclaiming it from constant notifications requires design, not just willpower.",
  "finding-ritual-in-the-kitchen": "How turning cooking into a sensory practice can ground you in the present moment and feed more than the body.",
  "the-gentle-discipline-of-saying-no": "Every yes carries a hidden no. Learning to decline with clarity and kindness is the boundary that lets your yes mean something.",
  "cultivating-a-mindful-workspace": "Your workspace shapes your attention. A few intentional changes to what you see and touch can shift the texture of an entire day.",
  "the-art-of-doing-nothing": "Why rest is not laziness, and how learning to be still changed the way I move through my days.",
  "morning-rituals-that-anchor-me": "A simple sequence of small acts that turns the first hour of the day into something sacred.",
  "letting-go-of-perfect": "Perfectionism kept me busy but never at peace. Here is what happened when I stopped chasing it.",
  "the-quiet-power-of-a-slow-morning": "What happens when you stop rushing through the first hours of your day and let them unfold at their own pace.",
  "breathing-through-the-overwhelm": "When everything feels like too much, three breaths can change the entire shape of the moment.",
  "seasonal-living-as-practice": "Aligning your rhythms with the natural world is one of the gentlest forms of self-care I know.",
  "the-weight-of-being-available": "On the quiet exhaustion of a life with no boundaries between reachable and resting.",
  "what-i-mean-when-i-say-gentle": "Gentleness is not weakness. It is the strongest way I know to move through a hard world.",
  "learning-to-sit-with-discomfort": "The urge to fix, flee, or distract is strong. But some feelings just need a witness.",
  "the-myth-of-balance": "Balance is not a destination. It is a shifting conversation about what needs your attention right now.",
};
