/**
 * Canonical display order for the journal index page (newest first).
 * This is the single source of truth for article ordering.
 */
export const ENTRY_ORDER = [
  "the-hours-that-belong-to-someone-else",
  "the-arithmetic-of-worry",
  "what-the-illness-left-behind",
  "the-thing-you-make-badly",
  "the-door-you-close-quietly",
  "what-the-empty-shelf-knows",
  "the-city-that-does-not-know-you-yet",
  "when-the-body-slows",
  "the-small-hand-that-pulls-you-back",
  "the-weather-inside-a-decision",
  "the-hours-no-one-sees",
  "what-the-mirror-does-not-show",
  "the-courage-of-staying-still",
  "the-taste-of-enough",
  "what-the-body-holds-after",
  "the-edges-of-attention",
  "hands-that-remember",
  "the-conversation-you-are-not-having",
  "the-intelligence-of-exhaustion",
  "the-practice-of-apologizing",
  "money-scarcity-and-enough",
  "living-alongside-pain",
  "anger-as-information",
  "the-sound-of-your-own-voice",
  "the-body-you-are-in",
  "rest-is-not-recovery",
  "on-friendships-that-change-shape",
  "the-permission-to-weep",
  "the-page-that-listens",
  "water-as-teacher",
  "learning-to-be-a-beginner",
  "the-freedom-of-small-spaces",
  "hunger-beyond-food",
  "the-ritual-of-repair",
  "on-grief-without-a-name",
  "what-the-garden-teaches",
  "the-practice-of-receiving",
  "silence-as-a-language",
  "the-kindness-of-routine",
  "sleep-as-surrender",
  "tending-the-inner-weather",
  "the-long-exhale",
  "on-walking-without-a-destination",
  "the-body-keeps-a-quiet-score",
  "the-art-of-gentle-transitions",
  "digital-minimalism-in-a-loud-world",
  "finding-ritual-in-the-kitchen",
  "the-gentle-discipline-of-saying-no",
  "cultivating-a-mindful-workspace",
  "the-art-of-doing-nothing",
  "morning-rituals-that-anchor-me",
  "letting-go-of-perfect",
  "the-quiet-power-of-a-slow-morning",
  "breathing-through-the-overwhelm",
  "seasonal-living-as-practice",
  "the-weight-of-being-available",
  "what-i-mean-when-i-say-gentle",
  "learning-to-sit-with-discomfort",
  "the-myth-of-balance",
];

/**
 * Curated featured article slugs for the home page hero section.
 * The home page displays the first N of these.
 */
export const HOME_FEATURED = [
  "the-practice-of-apologizing",
  "the-permission-to-weep",
  "living-alongside-pain",
  "anger-as-information",
  "the-body-you-are-in",
  "the-page-that-listens",
];
